name: nightly ws-server

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      windows-artifact-name: input-overlay-ws-windows
      linux-artifact-name: input-overlay-ws-linux
      retention-days: 60
